### ISSUE TITLE
No "calibtool" anywhere

### ISSUE THREAD

**Issue by fnorf** [rjw57/calibtools#1]
I might be stupid but I cannot figure out how to use this. =(

According to the documentation I should end up with an executable "calibtools" but it is nowhere to be found. I am on Archlinux. Tried installing both via pip as with a git clone. In both cases I get files: calib.py, tool.py, undistort.py, util.py.

It seems to work if I run tool.py directly though, is that the intended way?

**Comment by rjw57** [comment]
> According to the documentation I should end up with an executable "calibtools" but it is nowhere to be found. 

Does `pip install`-ing other command line tools work for you?

On my Fedora box, if I `pip install`, the script is installed to `~/.local/bin`:

``` console
$ pip install --user git+https://github.com/rjw57/calibtools
... stuff ...
$ which calibtools
~/.local/bin/calibtools
```

> Tried installing both via pip as with a git clone. In both cases I get files: calib.py, tool.py, undistort.py, util.py.

`git clone` is not a method of installation so I don't know what you mean by this. `git clone` is used for getting a copy of the source code. Unless you want to modify the code, `pip install` should be what you want.

**Comment by rjw57** [comment]
> In both cases I get files: calib.py, tool.py, undistort.py, util.py.

That's the source code. You appear to be confused about the difference between a Python script and an installable Python package.

> It seems to work if I run tool.py directly though, is that the intended way?

No. It may work, but if you want to "run" tool.py directly, the correct way would be

``` console
$ python -m calibtools.tool
```

**Comment by fnorf** [comment]
Sorry, PEBKAC. I have calibtools in ~/.local/bin/calibtools. Not sure why I did not find earlier. Time to add that to my path. ;)

Thank you!

**Comment by rjw57** [comment]
Excellent. Glad the problem's been solved.
